"""initial_postgres_schema

Revision ID: 1932aba8eb9e
Revises: 
Create Date: 2026-06-19 16:36:02.687316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1932aba8eb9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_sub', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('dates', sa.Text(), nullable=False),
    sa.Column('origin_city', sa.Text(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trips_user_updated', 'trips', ['user_id', 'updated_at'], unique=False)
    op.create_table('user_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('llm_api_key_enc', sa.Text(), nullable=True),
    sa.Column('llm_base_url', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('rebuild_scope', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('node_timings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_trip', 'agent_runs', ['trip_id'], unique=False)
    op.create_table('itinerary_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('program_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'version', name='uq_itinerary_trip_version')
    )
    op.create_table('section_artifacts',
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'section')
    )
    op.create_table('trip_preferences',
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('graph_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('graph_run_id', sa.Text(), nullable=True),
    sa.Column('city_fact_status', sa.Text(), server_default='idle', nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['itinerary_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_runs_trip_status', 'graph_runs', ['trip_id', 'status'], unique=False)
    op.create_index('idx_graph_runs_user', 'graph_runs', ['user_id'], unique=False)
    op.create_table('program_item_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('itinerary_version_id', sa.BigInteger(), nullable=True),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('vote IN (1, -1)', name='ck_program_feedback_vote'),
    sa.ForeignKeyConstraint(['itinerary_version_id'], ['itinerary_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'section', 'item_key', name='uq_program_feedback_item')
    )
    op.create_index('idx_program_feedback_trip', 'program_item_feedback', ['trip_id'], unique=False)
    op.create_table('tool_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('itinerary_version_id', sa.BigInteger(), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('live_data', sa.Boolean(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('raw_results_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_version_id'], ['itinerary_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_runs_trip', 'tool_runs', ['trip_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=True),
    sa.Column('graph_run_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_events_user_created', 'usage_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            """
            INSERT INTO users (id, email, password_hash, google_sub, created_at, updated_at)
            VALUES (1, 'system@local', NULL, NULL, NOW(), NOW())
            ON CONFLICT (email) DO NOTHING
            """
        )
    )
    op.execute(sa.text("SELECT setval(pg_get_serial_sequence('users', 'id'), GREATEST(1, (SELECT MAX(id) FROM users)))"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_events_user_created', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('idx_tool_runs_trip', table_name='tool_runs')
    op.drop_table('tool_runs')
    op.drop_index('idx_program_feedback_trip', table_name='program_item_feedback')
    op.drop_table('program_item_feedback')
    op.drop_index('idx_graph_runs_user', table_name='graph_runs')
    op.drop_index('idx_graph_runs_trip_status', table_name='graph_runs')
    op.drop_table('graph_runs')
    op.drop_table('trip_preferences')
    op.drop_table('section_artifacts')
    op.drop_table('itinerary_versions')
    op.drop_index('idx_agent_runs_trip', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('user_settings')
    op.drop_table('user_profile')
    op.drop_index('idx_trips_user_updated', table_name='trips')
    op.drop_table('trips')
    op.drop_index('idx_audit_events_user_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    # ### end Alembic commands ###
