"""SQLite-хранилище поездок и версий программы."""

from db.connection import get_database_path, init_db
from db.repository import (
    PlannedTripSummary,
    TripSummary,
    create_trip,
    delete_item_feedback,
    delete_trip,
    ensure_user_profile_from_trips,
    get_itinerary_version,
    get_latest_itinerary,
    get_preferences,
    get_trip,
    get_user_profile,
    has_user_profile,
    list_item_feedback,
    list_item_feedback_by_index,
    list_planned_trips,
    list_tool_runs,
    list_trips,
    list_agent_runs,
    log_tool_run,
    log_agent_run,
    mark_latest_itinerary_approved,
    save_itinerary_version,
    save_preferences,
    save_section_artifact,
    save_user_profile,
    get_section_artifact,
    update_trip_status,
    upsert_item_feedback,
)

__all__ = [
    "PlannedTripSummary",
    "TripSummary",
    "create_trip",
    "delete_item_feedback",
    "delete_trip",
    "ensure_user_profile_from_trips",
    "get_database_path",
    "get_itinerary_version",
    "get_latest_itinerary",
    "get_preferences",
    "get_trip",
    "get_user_profile",
    "has_user_profile",
    "init_db",
    "list_item_feedback",
    "list_item_feedback_by_index",
    "list_planned_trips",
    "list_agent_runs",
    "list_tool_runs",
    "list_trips",
    "log_agent_run",
    "log_tool_run",
    "mark_latest_itinerary_approved",
    "save_itinerary_version",
    "save_preferences",
    "save_section_artifact",
    "save_user_profile",
    "get_section_artifact",
    "update_trip_status",
    "upsert_item_feedback",
]
